[mainpage]
title = "BoltHumanoid drivers for robot_interfaces"
auto_general_docs = false

[intersphinx.mapping]
robot_interfaces = "https://open-dynamic-robot-initiative.github.io/robot_interfaces"
bolt = "https://open-dynamic-robot-initiative.github.io/bolt"
